import Head from 'next/head';
import { FormField } from '@/components/form/FormField';
import { BooleanInputProperties } from '@/components/form/input/BooleanInput';
import { SelectInputProperties } from '@/components/form/input/SelectInput';
import styles from '../styles/Home.module.css';
import { FieldTypeEnum } from '@/types/genericInputProps';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>✨ Input Factory ✨</h1>

        <FormField
          label="Text"
          input={{
            type: FieldTypeEnum.TEXT,
          }}
        />

        <FormField
          label="Select"
          input={{
            type: FieldTypeEnum.SELECT,
            properties: {
              options: [
                { value: 'opt1', label: 'Option 1' },
                { value: 'opt2', label: 'Option 2' },
                { value: 'opt3', label: 'Option 3' },
              ],
            } as SelectInputProperties,
          }}
        />

        <FormField
          label="Checkbox"
          input={{
            type: FieldTypeEnum.BOOLEAN,
            properties: {
              defaultChecked: true,
            } as BooleanInputProperties,
          }}
        />

        <FormField
          label="Radio 1"
          input={{
            type: FieldTypeEnum.BOOLEAN,
            properties: {
              id: 'radio1',
              name: 'radioInput',
              inputType: 'radio',
            } as BooleanInputProperties,
          }}
        />

        <FormField
          label="Radio 2"
          input={{
            type: FieldTypeEnum.BOOLEAN,
            properties: {
              id: 'radio2',
              name: 'radioInput',
              inputType: 'radio',
            } as BooleanInputProperties,
          }}
        />

        <FormField
          label="Radio 3"
          input={{
            type: FieldTypeEnum.BOOLEAN,
            properties: {
              id: 'radio3',
              name: 'radioInput',
              inputType: 'radio',
            } as BooleanInputProperties,
          }}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Kirill Kazakov{' '}
        </a>
      </footer>
    </div>
  );
}
